kind: Service
apiVersion: v1
metadata:
  name: lb-svc
spec:
  type: LoadBalancer
  externalIPs:
     - 172.16.0.14
  selector:
    app: ingress-nginx-controller
  ports:
   - name: node
     port: 80
     targetPort: 80
